name: CI_Python_module

on:
  pull_request:
    branches: [ "develop", "main" ]
  workflow_dispatch:

jobs:
  test_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
  
      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip list

      - name: Run Python script and tests
        working-directory: ./backend
        run: |
          source venv/bin/activate
          python app.py &
          pytest
