name: CI_Python_module

on:
  pull_request:
    branches: [ "develop", "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
  
      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip list

      - name: Pull PostgreSQL Image
        run: docker pull jmuhlema/postgresql:16
        
      - name: Run PostgreSQL Container
        run: |
          docker run -d --name pdg-postgresql \
            -e POSTGRESQL_USERNAME=pdg \
            -e POSTGRESQL_PASSWORD=pdg \
            -e POSTGRESQL_DATABASE=pdg_db \
            -e POSTGRESQL_POSTGRES_PASSWORD=root \
            -p 5432:5432 jmuhlema/postgresql:16

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          sleep 10

      - name: Run Python script and tests
        working-directory: ./backend
        run: |
          source venv/bin/activate
          python app.py &
          sleep 10
          pytest

      - name: Stop and remove PostgreSQL Container
        if: always()
        run: |
          docker stop pdg-postgresql
          docker rm pdg-postgresql
